name: PR build for Web

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests for Web
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Check if files in packages/web have changed
      - name: Check for changes in web
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --quiet origin/${{ github.base_ref }} -- packages/web || echo "changes-detected"
      - name: Skip tests if no changes
        if: steps.changes.outputs.changes-detected != 'true'
        run: echo "No changes detected in packages/web. Skipping tests."

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        working-directory: packages/web
        run: yarn install

      # Run tests
      - name: Run tests
        working-directory: packages/web
        run: yarn test

  build:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Check if files in packages/web have changed
      - name: Check for changes in web
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --quiet origin/${{ github.base_ref }} -- packages/web || echo "changes-detected"
      - name: Skip build if no changes
        if: steps.changes.outputs.changes-detected != 'true'
        run: echo "No changes detected in packages/web. Skipping build."

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        working-directory: packages/web
        run: yarn install

      # Build the project
      - name: Build project
        working-directory: packages/web
        run: yarn build
