name: main build for Web

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests for Web
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        working-directory: packages/web
        run: yarn install

      # Run tests
      - name: Run tests
        working-directory: packages/web
        run: yarn test

  build:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      # Install dependencies
      - name: Install dependencies
        working-directory: packages/web
        run: yarn install

      # Build the project
      - name: Build project
        working-directory: packages/web
        run: yarn build
